#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information() {
    local subdomain="$1"
    local domain="$2"
    local record_type=$(dig "$subdomain.$domain" +short)
    local ip=$(dig "$subdomain.$domain" +short)
    
    if [[ -n "$record_type" && -n "$ip" ]]; then
        printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record_type" "$ip"
    else
        printf "No information found for the subdomain %s\n" "$subdomain"
    fi
}

if [[ "$#" == 1 ]]; then
  domain_information "www" "$1"
  domain_information "lb-01" "$1"
  domain_information "web-01" "$1"
  domain_information "web-02" "$1"
elif [[ "$#" == 2 ]]; then
  domain_information "$2" "$1"
fi
