#!/usr/bin/env bash
# Ensure correct number of arguments and transfer the file to the server
if (( $# < 4 )); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
