#!/usr/bin/env bash

# Ensure correct number of arguments
if (( $# < 4 )); then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Transfer the file to the server
scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
