#!/usr/bin/env bash
# Script that installs Nginx and configures it to serve "Hello World!" content
apt update -y
apt install -y nginx

cat << EOF > /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Hello World!</title>
</head>
<body>
  <h1>Hello World!</h1>
</body>
</html>
EOF
systemctl restart nginx
