#!/usr/bin/env bash
# Install NGINX and configure redirection
# Update package list
apt-get update
apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF
systemctl restart nginx
