#!/usr/bin/env bash
# Installs Nginx with the identical configuration to the previous task server  `web-01`

sudo apt remove --purge nginx nginx-full nginx-common -y

sudo apt update
sudo apt install nginx -y

sudo tee /var/www/html/index.html > /dev/null <<EOT
Hello World!
EOT

sudo tee /var/www/html/error404.html > /dev/null <<EOT
Ceci n'est pas une page
EOT

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    error_page 404 /error404.html;
    server_name _;

    add_header X-Served-By \$hostname;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
    }
}
EOT

sudo service nginx restart
