#!/usr/bin/env bash
# configures a HAproxy on a server of New Ubuntu machine
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 138923-web-01 54.160.108.69 check
        server 138923-web-02 35.175.135.230 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
