#!/usr/bin/env bash
# configures a HAproxy on a server of New Ubuntu machine

sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 138923-web-01 54.160.108.69:80 check
        server 138923-web-02 35.175.135.230:80 check
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
