#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it
mysqldump -uroot -p"$1" --all-databases > backup.sql && mysql -uroot -p"$1" < backup.sql && rm backup.sql
tar -czf "$(date +%d-%m-%Y).tar.gz" backup.sql
