#!/usr/bin/env bash
# Script displays a list of currently running processes:
#   it shows all processes, for all users, including those
#+  which might not have a TTY in user-oriented format.
ps -auxf
