#!/usr/bin/env bash
# Script that:
#   Creates the file /var/run/holbertonscript.pid containing its PID
#   Displays To infinity and beyond indefinitely 
#   Displays I hate the kill command when receiving a SIGTERM signal
#   Displays Y U no love me?! when receiving a SIGINT signal
#   Deletes the file /var/run/holbertonscript.pid
#   and terminates itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/holbertonscript.pid"

terminate() {
  rm "$pid_file"
  exit
}

echo "$$" > "$pid_file"

while true; do
  echo "To infinity and beyond"
  sleep 2

  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminate' SIGTERM
  trap 'terminate' SIGQUIT
done
