#!/usr/bin/env bash
# Script displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Best School" then "Hi".
counter=1
while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Hi"
  fi

  echo "Best School"
  counter=$((counter+1))
done
