#!/usr/bin/env bash
# Script displays the time for 12 horus and 59 minutes:
#   hours from 0 to 12
#   minutes from 1 to 59
hours=0
minute=1

while [ $hours -le 12 ]
do
  echo "Hour: $hours"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    minute=$((minute+1))
  done
  hours=$((hours+1))
done
