#!/usr/bin/env bash
# Script displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash
dir_cont=0
List=$(ls)
for dir_cont in $List
do
    echo "$dir_cont" | cut -d "-" -f2
done
