#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
# Change nginx user

sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
# Configure nginx to listen on all active IPs on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
# Restart nginx service
service nginx restart
