#!/usr/bin/env bash
# Modify Apache and Nginx configuration
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart Apache gracefully
pkill -1 apache2

# Set permissions and restart Nginx as the 'nginx' user
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
