#!/usr/bin/env bash
# Modify Apache and Nginx configuration
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2

if [ $? -eq 0 ]; then
	sleep 1
	chmod ugo+r /etc/nginx/nginx.conf
	chmod ugo+r /etc/nginx/sites-available/default
	sudo -u nginx service nginx restart
fi
